import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import { ageAt, contestConfig, contestState, creativeTools, emptyEntry, isMinor, safeUrl, validateEntry, wordCount, type Entry } from './config'
import { submitEntry, track } from './api'
import { Terms } from './Terms'
const steps=['Sobre vos','Tu propuesta','Entrega','Proceso creativo','Autorización','Declaraciones','Revisión']
const stepHints=['Esta convocatoria es exclusiva para habitantes del departamento de Flores. Completá tus datos y tu localidad de residencia.','No necesitás palabras técnicas: contanos tu idea con tus propias palabras.','Elegí la opción que te resulte más cómoda: archivo o enlace.','Contanos cómo creaste tu diseño.','Completá este paso con tu adulto responsable.','Leé estas declaraciones antes de aceptarlas.','Ya falta poco. Revisá todo antes de enviar.']
const declarations = {authorship_accepted:'Declaro que la propuesta presentada es de mi autoría y/o que poseo los derechos necesarios sobre todos sus elementos.',rights_accepted:'Declaro que el trabajo no vulnera derechos de terceros.',terms_accepted:'Confirmo que leí y acepto las Bases y Condiciones del concurso.',institutional_use_accepted:'En caso de resultar ganador/a, autorizo la utilización institucional del diseño conforme a las Bases y Condiciones.'} as const
function FileInput({label,file,onChange,error,id}:{label:string;file:File|null;onChange:(f:File|null)=>void;error?:string;id:string}) {
  const [preview,setPreview]=useState('')
  useEffect(()=>{if(!file || !file.type.startsWith('image/')){setPreview('');return};const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file])
  return <div className="drop" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onChange(e.dataTransfer.files[0]||null)}}><label htmlFor={id}>{label}</label><p className="muted">Arrastrá un archivo o seleccionalo. PNG, JPG/JPEG o PDF · hasta 10 MB.</p><input id={id} type="file" accept=".png,.jpg,.jpeg,.pdf" aria-describedby={`${id}-error`} aria-invalid={Boolean(error)} onChange={e=>{onChange(e.target.files?.[0]||null);e.target.value=''}}/>{file && <><p>{file.name} · {(file.size/1024/1024).toFixed(2)} MB · {file.type}</p>{preview && <img src={preview} alt="Vista previa de tu propuesta"/>}<button className="btn secondary" type="button" onClick={()=>onChange(null)}>Eliminar archivo</button><p className="muted">Seleccioná otro archivo para reemplazarlo. Pendiente de envío.</p></>}<p id={`${id}-error`} className="error">{error}</p></div>
}
export function ContestForm() {
  const [entry,setEntry]=useState<Entry>(emptyEntry),[step,setStep]=useState(0),[errors,setErrors]=useState<Record<string,string>>({})
  const [main,setMain]=useState<File|null>(null),[additional,setAdditional]=useState<File|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[code,setCode]=useState('')
  const lock=useRef(false), token=useRef(crypto.randomUUID()), heading=useRef<HTMLHeadingElement>(null), started=useRef(false)
  useEffect(()=>{if(step>0 || code)heading.current?.focus()},[step,code])
  const set = <K extends keyof Entry>(key:K,value:Entry[K]) => {setEntry(e=>({...e,[key]:value}));if(!started.current){started.current=true;void track('form_started')}}
  function input(key:keyof Entry,label:string,type='text',required=true) {return <div><label htmlFor={`mr-${key}`}>{label}{required?' *':''}</label><input id={`mr-${key}`} type={type} value={String(entry[key])} maxLength={2000} aria-invalid={Boolean(errors[key])} aria-describedby={`error-${key}`} onChange={e=>{set(key,e.target.value as never);if(key==='birth_date' && e.target.value)set('age',String(ageAt(e.target.value)))}}/><p id={`error-${key}`} className="error">{errors[key]}</p></div>}
  function textArea(key:'proposal_description'|'palette'|'ai_details',label:string) {return <div><label htmlFor={`mr-${key}`}>{label} *</label><textarea id={`mr-${key}`} rows={5} value={entry[key]} maxLength={key==='proposal_description'?15000:2000} onChange={e=>set(key,e.target.value)} aria-invalid={Boolean(errors[key])} aria-describedby={`error-${key}`}/><p className="error" id={`error-${key}`}>{errors[key]}</p></div>}
  function checkFiles() {const e:Record<string,string>={};if(entry.submission_method==='file'){if(!main)e.main='Seleccioná el diseño principal.';for(const [key,file] of [['main',main],['additional',additional]] as const){if(file && (!contestConfig.mimeTypes.includes(file.type)||! /\.(png|jpe?g|pdf)$/i.test(file.name)||file.size>contestConfig.maxFileBytes || file.size===0))e[key]='Usá un PNG, JPG o PDF válido, de hasta 10 MB.'}}return e}
  function next() {const e={...validateEntry(entry,step),...(step===2?checkFiles():{})};setErrors(e);if(Object.keys(e).length){setMessage('Falta completar o corregir algún dato. Revisá los campos señalados; lo que escribiste sigue guardado en esta página.');requestAnimationFrame(()=>document.querySelector<HTMLElement>('.form [aria-invalid="true"]')?.focus());return};setMessage('');setStep(s=>s===3&&!isMinor(entry)?5:s+1)}
  async function send() {
    if(lock.current)return
    const e={...validateEntry(entry),...checkFiles()};setErrors(e)
    if(Object.keys(e).length){setMessage('Revisá los campos indicados antes de enviar.');setStep(0);return}
    if(contestState()!=='open'){setMessage('La convocatoria no está abierta.');return}
    lock.current=true;setBusy(true);setMessage('Estamos enviando tu propuesta…')
    try{setCode(await submitEntry(entry,main,additional,token.current));void track('form_completed');setMessage('')}catch(err){setMessage(err instanceof Error?err.message:'No pudimos enviar. Tus datos siguen en pantalla.')}finally{setBusy(false);lock.current=false}
  }
  if(code)return <div className="receipt"><h2 ref={heading} tabIndex={-1}>¡Recibimos tu propuesta!</h2><p>Gracias por participar del {contestConfig.title} por el {contestConfig.subtitle}.</p><strong>{code}</strong><p>Guardá este código. Te permitirá identificar tu inscripción si necesitás realizar una consulta.</p><Link className="btn" to="/">Volver al inicio</Link><a className="btn secondary" href="#compartir">Compartir el concurso / enviar por WhatsApp</a></div>
  return <form className="form card" noValidate onSubmit={e=>e.preventDefault()} onKeyDown={e=>{if(e.key==='Enter' && e.target instanceof HTMLInputElement)e.preventDefault()}}>
    <p className="eyebrow">Tu creatividad puede representarnos · Paso {step+1} de {steps.length}</p><h2 ref={heading} tabIndex={-1}>{steps[step]}</h2><p className="step-hint">{stepHints[step]}</p><progress className="form-progress" value={step+1} max={steps.length} aria-label={`Paso ${step+1} de ${steps.length}: ${steps[step]}`}/><ol className="steps" aria-label="Pasos del formulario">{steps.map((s,i)=><li key={s} aria-current={step===i?'step':undefined}>{i+1}. {s}</li>)}</ol><p className="muted">* Campos obligatorios. Podés volver a los pasos anteriores para corregir. Tus datos se conservan mientras permanezcas en esta página.</p>
    <fieldset disabled={busy}>
    {step===0 && <div className="grid">{input('full_name','Nombre completo')}{input('birth_date','Fecha de nacimiento','date')}{input('age','Edad','number')}{input('city','Localidad / ciudad de residencia en Flores')}<div><label htmlFor="mr-department">Departamento de residencia *</label><input id="mr-department" value={contestConfig.eligibleDepartment} readOnly aria-describedby="residence-help department-error"/><p id="residence-help" className="muted">Solo pueden participar habitantes de Flores.</p><p id="department-error" className="error">{errors.department}</p></div>{input('phone','Teléfono de contacto','tel')}{input('email','Correo electrónico','email')}</div>}
    {step===1 && <>{input('proposal_name','Nombre de la propuesta','text',false)}{textArea('proposal_description','Contanos cuál es la idea de tu diseño')}<p className="muted" aria-live="polite">{wordCount(entry.proposal_description)} / 500 palabras</p><p>¿Qué representa? ¿Por qué elegiste esos elementos? ¿Cómo se relaciona con las Mujeres Rurales y Flores?</p>{textArea('palette','Colores principales y su significado')}<p className="muted">No necesitás conocer códigos profesionales.</p></>}
    {step===2 && <><fieldset><legend>¿Cómo querés compartir tu propuesta?</legend>{(['file','link'] as const).map(v=><label className="check" key={v}><input type="radio" name="method" checked={entry.submission_method===v} onChange={()=>set('submission_method',v)}/>{v==='file'?'Subir archivos':'Compartir un enlace'}</label>)}</fieldset>{entry.submission_method==='file'?<><FileInput id="main" label="Diseño principal *" file={main} onChange={setMain} error={errors.main}/><FileInput id="additional" label="Material complementario (opcional)" file={additional} onChange={setAdditional} error={errors.additional}/></>:<>{input('external_main_url','Enlace al diseño','url')}{input('external_complementary_url','Enlace a material complementario','url',false)}<p className="notice">Verificá que el enlace permita acceder sin pedir autorización y que siga disponible durante la evaluación.</p>{safeUrl(entry.external_main_url)&&<a className="btn secondary" target="_blank" rel="noopener noreferrer" href={entry.external_main_url}>Probar enlace</a>}</>}</>}
    {step===3 && <><fieldset><legend>¿Qué herramientas utilizaste? *</legend>{creativeTools.map(t=><label className="check" key={t}><input type="checkbox" checked={entry.tools_used.includes(t)} onChange={e=>set('tools_used',e.target.checked?[...entry.tools_used,t]:entry.tools_used.filter(v=>v!==t))}/>{t}</label>)}<p className="error">{errors.tools_used}</p></fieldset>{entry.tools_used.includes('Inteligencia artificial')&&textArea('ai_details','Contanos qué herramienta utilizaste y cómo la usaste')}<p className="notice">El uso de herramientas digitales o de inteligencia artificial debe declararse y no exime de cumplir los requisitos de autoría, originalidad y derechos de terceros.</p></>}
    {step===4 && <><p>Necesitás la autorización de madre, padre, tutor/a o responsable legal.</p>{input('guardian_name','Nombre completo del adulto responsable')}{input('guardian_document','Cédula / documento')}{input('guardian_phone','Teléfono','tel')}{input('guardian_email','Correo electrónico','email')}<label className="check"><input type="checkbox" checked={entry.guardian_accepted} onChange={e=>set('guardian_accepted',e.target.checked)}/>Autorizo la participación de la persona menor de edad en el concurso y acepto las Bases y Condiciones, incluida la utilización institucional de la propuesta ganadora.</label><p className="error">{errors.guardian_accepted}</p></>}
    {step===5 && <>{Object.entries(declarations).map(([k,label])=><div key={k}><label className="check"><input type="checkbox" checked={entry[k as keyof typeof declarations]} onChange={e=>set(k as keyof typeof declarations,e.target.checked)}/>{label}</label><p className="error">{errors[k]}</p></div>)}<details onToggle={e=>{if(e.currentTarget.open)void track('terms')}}><summary>Leer Bases y Condiciones sin salir del formulario</summary><Terms/></details></>}
    {step===6 && <><h3>Revisá tu propuesta</h3><dl>{[['Nombre',entry.full_name],['Correo',entry.email],['Localidad',`${entry.city}, ${entry.department}`],['Propuesta',entry.proposal_name||'Sin título'],['Entrega',entry.submission_method==='file'?`${main?.name}${additional?' / '+additional.name:''}`:entry.external_main_url],['Material complementario',entry.external_complementary_url||'—'],['Bases','Aceptadas'],['Autorización de menor',isMinor(entry)?'Aceptada':'No corresponde']].map(([k,v])=><div className="notice" key={k}><dt><strong>{k}</strong></dt><dd style={{overflowWrap:'anywhere'}}>{v}</dd></div>)}</dl><p>Los datos ingresados serán utilizados exclusivamente para la gestión del concurso y las comunicaciones vinculadas a esta convocatoria. Las propuestas y los datos personales no serán publicados automáticamente.</p></>}
    </fieldset><p role="status" aria-live="polite" className="notice">{message || `Paso ${step+1} de ${steps.length}`}</p><div className="actions">{step>0&&<button type="button" className="btn secondary" disabled={busy} onClick={()=>{setStep(s=>s===5&&!isMinor(entry)?3:s-1);setMessage('')}}>Volver y editar</button>}{step<6?<button type="button" className="btn" onClick={next}>Continuar</button>:<button type="button" className="btn" disabled={busy} onClick={()=>void send()}>{busy?'Estamos enviando tu propuesta…':'Enviar propuesta'}</button>}</div>
  </form>
}
