import { useCallback, useEffect, useState } from 'react'
import { supabase } from '../lib/supabase'
import { criteria, safeUrl, statuses } from './config'
import { signedFile, type Result, type Submission } from './api'
import './contest.css'
type Evaluation={juror_id:string;scores:number[];notes:string;updated_at:string}
function Detail({item,onBack,onSaved}:{item:Submission;onBack:()=>void;onSaved:()=>void}) {
  const [status,setStatus]=useState(item.status),[notes,setNotes]=useState(item.internal_notes||''),[scores,setScores]=useState<number[]>(criteria.map(()=>0)),[evaluationNotes,setEvaluationNotes]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[evaluations,setEvaluations]=useState<Evaluation[]>([]),[userId,setUserId]=useState(''),[link,setLink]=useState('')
  useEffect(()=>{if(!supabase)return;void supabase.auth.getUser().then(async({data})=>{if(!data.user)return;setUserId(data.user.id);const response=await supabase!.from('rural_women_evaluations').select('*').eq('submission_id',item.id);if(response.error){setMessage('No se pudieron cargar las evaluaciones.');return};setEvaluations(response.data||[]);const own=response.data?.find(e=>e.juror_id===data.user!.id);if(own){setScores(own.scores);setEvaluationNotes(own.notes)}})},[item.id])
  async function save(evaluation=false) {if(!supabase||busy)return;setBusy(true);setMessage('');try{const r=evaluation?await supabase.from('rural_women_evaluations').upsert({submission_id:item.id,juror_id:userId,scores,notes:evaluationNotes},{onConflict:'submission_id,juror_id'}):await supabase.from('rural_women_logo_submissions').update({status,internal_notes:notes}).eq('id',item.id).select('id').single();if(r.error)throw r.error;setMessage('Cambios guardados.');onSaved()}catch{setMessage('No se pudo guardar. Verificá tus permisos y los valores.')}finally{setBusy(false)}}
  async function openFile(path:string) {try{setLink(await signedFile(path))}catch{setMessage('No se pudo abrir el archivo.')}}
  return <div className="card admin-detail"><button className="btn secondary" onClick={onBack}>← Volver al listado</button><h2>{item.submission_code} · {item.proposal_name||'Sin título'}</h2><dl>{Object.entries(item).filter(([k])=>!['request_token','id','main_file_url','complementary_file_url','internal_notes','status'].includes(k)).map(([k,v])=><div key={k}><dt>{({full_name:'Participante',birth_date:'Fecha de nacimiento',age:'Edad',city:'Localidad',department:'Departamento',phone:'Teléfono',email:'Correo',proposal_description:'Memoria conceptual',palette:'Paleta',tools_used:'Herramientas',ai_details:'Uso de IA',guardian_name:'Responsable legal',guardian_document:'Documento del responsable',guardian_phone:'Teléfono del responsable',guardian_email:'Correo del responsable',created_at:'Recibida',terms_version:'Versión de bases'} as Record<string,string>)[k]||k.replaceAll('_',' ')}</dt><dd>{Array.isArray(v)?v.join(', '):typeof v==='boolean'?v?'Sí':'No':String(v??'—')}</dd></div>)}</dl><div className="actions">{item.main_file_url&&<button className="btn" onClick={()=>void openFile(item.main_file_url!)}>Ver / descargar diseño</button>}{item.complementary_file_url&&<button className="btn" onClick={()=>void openFile(item.complementary_file_url!)}>Ver / descargar material complementario</button>}{[item.external_main_url,item.external_complementary_url].filter(v=>v&&safeUrl(v)).map(v=><a className="btn secondary" href={v!} key={v} target="_blank" rel="noopener noreferrer">Abrir enlace externo</a>)}</div>{link&&<p className="notice"><a className="file-link" target="_blank" rel="noopener noreferrer" href={link}>Abrir archivo privado (enlace válido por 2 minutos)</a></p>}<label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}>{Object.entries(statuses).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Nota interna<textarea value={notes} maxLength={5000} onChange={e=>setNotes(e.target.value)}/></label><button className="btn" disabled={busy} onClick={()=>void save()}>Guardar revisión</button>
  <section><h2>Mi evaluación</h2><p>Las calificaciones de otras personas permanecen ocultas hasta que el equipo habilite la puesta en común.</p><div className="grid">{criteria.map(([label,max],i)=><label key={label}>{label} · 0–{max}<input type="number" min={0} max={max} step={1} value={scores[i]} onChange={e=>setScores(a=>a.map((n,j)=>j===i?Number(e.target.value):n))}/></label>)}</div><h3>Total: {scores.reduce((a,b)=>a+b,0)} / 100</h3><label>Fundamentación del jurado<textarea value={evaluationNotes} maxLength={5000} onChange={e=>setEvaluationNotes(e.target.value)}/></label><button className="btn" disabled={busy||!userId||scores.some((v,i)=>!Number.isInteger(v)||v<0||v>criteria[i][1])} onClick={()=>void save(true)}>Guardar mi evaluación</button>{evaluations.filter(e=>e.juror_id!==userId).map(e=><div className="notice" key={e.juror_id}>Jurado {e.juror_id}: {e.scores.reduce((a,b)=>a+b,0)}/100<p>{e.notes}</p></div>)}</section><p role="status">{message}</p></div>
}
function ResultEditor() {
  const [result,setResult]=useState<Result|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
  useEffect(()=>{if(supabase)void supabase.from('rural_women_results').select('*').eq('id',1).single().then(({data,error})=>{if(error)setMessage('No se pudo cargar la configuración de resultados.');else setResult(data)})},[])
  async function save(){if(!result||!supabase)return;if(result.published && (!result.proposal_name||!result.author||!result.rationale||!safeUrl(result.image_url)||!result.image_url.startsWith('https://'))){setMessage('Completá nombre, autoría, fundamentación y un enlace HTTPS al diseño autorizado para difusión.');return}setBusy(true);const {error}=await supabase.from('rural_women_results').update(result).eq('id',1).select('id').single();setMessage(error?'No se pudo guardar.':'Configuración guardada.');setBusy(false)}
  return <details><summary>Resultado público y puesta en común del jurado</summary>{result&&<><p className="notice">Publicá únicamente la información autorizada para difusión. No uses enlaces firmados del almacenamiento privado. El resultado se mostrará al marcar “Publicar resultado” y guardar.</p>{(['proposal_name','author','image_url','rationale','mentions'] as const).map((k,i)=><label key={k}>{['Nombre de la propuesta','Autor/a para difusión pública','URL HTTPS de la imagen pública autorizada','Fundamentación','Menciones especiales'][i]}<textarea value={result[k]} onChange={e=>setResult({...result,[k]:e.target.value})}/></label>)}{safeUrl(result.image_url)&&<img className="preview" src={result.image_url} alt="Vista previa del resultado a publicar"/>}<label className="check"><input type="checkbox" checked={result.evaluations_released} onChange={e=>setResult({...result,evaluations_released:e.target.checked})}/>Permitir al equipo comparar las evaluaciones de todos los jurados</label><label className="check"><input type="checkbox" checked={result.published} onChange={e=>setResult({...result,published:e.target.checked})}/>Publicar resultado</label><button className="btn" disabled={busy} onClick={()=>void save()}>Guardar configuración</button></>}<p role="status">{message}</p></details>
}
export function ContestAdmin() {
  const [items,setItems]=useState<Submission[]>([]),[selected,setSelected]=useState<Submission|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[events,setEvents]=useState<Record<string,number>>({})
  const [filters,setFilters]=useState({search:'',status:'',city:'',department:'',age:'',minor:'',method:'',ai:'',from:'',to:''})
  const load=useCallback(async()=>{if(!supabase)return;setBusy(true);setMessage('');try{const rows:Submission[]=[];for(let offset=0;;offset+=1000){const {data,error}=await supabase.from('rural_women_logo_submissions').select('*').order('created_at',{ascending:false}).range(offset,offset+999);if(error)throw error;rows.push(...data);if(data.length<1000)break}setItems(rows);const counters:Record<string,number>={};for(const event of ['visit','start_click','terms','download','share','form_started','form_completed']){const r=await supabase.from('rural_women_events').select('id',{count:'exact',head:true}).eq('event',event);if(r.error)throw r.error;counters[event]=r.count||0}setEvents(counters)}catch{setMessage('No se pudieron cargar los datos del concurso. Revisá la conexión y los permisos.')}finally{setBusy(false)}},[])
  useEffect(()=>{void load()},[load])
  const filtered=items.filter(p=>(!filters.search||`${p.full_name} ${p.proposal_name} ${p.submission_code}`.toLocaleLowerCase().includes(filters.search.toLocaleLowerCase()))&&(!filters.status||p.status===filters.status)&&(!filters.city||p.city.toLowerCase().includes(filters.city.toLowerCase()))&&(!filters.department||p.department===filters.department)&&(!filters.age||p.age===Number(filters.age))&&(!filters.minor||String(p.is_minor)===filters.minor)&&(!filters.method||p.submission_method===filters.method)&&(!filters.ai||String(p.ai_used)===filters.ai)&&(!filters.from||p.created_at.slice(0,10)>=filters.from)&&(!filters.to||p.created_at.slice(0,10)<=filters.to))
  function exportCsv(){const keys=['submission_code','full_name','age','city','department','email','phone','proposal_name','status','created_at'] as const;const cell=(v:unknown)=>{let s=String(v??'');if(/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'};const csv=[keys.join(','),...filtered.map(p=>keys.map(k=>cell(p[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='concurso-mujeres-rurales.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  return <section className="contest card" aria-label="Concurso Mujeres Rurales 2026"><h2>Concurso Mujeres Rurales 2026</h2><div className="actions"><button className="btn secondary" disabled={busy} onClick={()=>void load()}>Actualizar</button><button className="btn secondary" onClick={exportCsv} disabled={busy}>Exportar listado filtrado</button></div><p role="status">{busy?'Cargando propuestas…':message}</p><div className="grid">{[['Total recibidas',items.length],['Válidas',items.filter(p=>p.status==='valid').length],['Pendientes de revisión',items.filter(p=>['received','under_review','needs_review'].includes(p.status)).length],['Menores de edad',items.filter(p=>p.is_minor).length],['Por archivo',items.filter(p=>p.submission_method==='file').length],['Por enlace',items.filter(p=>p.submission_method==='link').length],['IA declarada',items.filter(p=>p.ai_used).length]].map(([k,v])=><div className="notice" key={k}><p>{k}</p><h3>{v}</h3></div>)}</div>
  <details><summary>Analítica de la sección</summary><p className="muted">Contadores orientativos de eventos, sin identificar visitantes. No equivalen a personas únicas.</p>{Object.entries(events).map(([k,v])=><p key={k}>{({visit:'Visitas',start_click:'Clics en presentar',terms:'Aperturas de bases',download:'Descargas',share:'Compartir',form_started:'Formularios iniciados',form_completed:'Confirmaciones'} as Record<string,string>)[k]}: {v}</p>)}</details><ResultEditor/>
  {selected?<Detail key={selected.id} item={selected} onBack={()=>setSelected(null)} onSaved={()=>void load()}/>:<><div className="grid">{(['search','city','department','age','from','to'] as const).map((k,i)=><label key={k}>{['Buscar nombre, propuesta o código','Localidad','Departamento','Edad','Desde','Hasta'][i]}<input type={['from','to'].includes(k)?'date':k==='age'?'number':'text'} value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}/></label>)}{([['status','Estado',Object.entries(statuses)],['minor','Edad legal',[['true','Menor'],['false','Adulto']]],['method','Entrega',[['file','Archivo'],['link','Enlace']]],['ai','IA declarada',[['true','Sí'],['false','No']]]] as [keyof typeof filters,string,string[][]][]).map(([k,label,options])=><label key={k}>{label}<select value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}><option value="">Todos</option>{options.map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>)}</div><p>{filtered.length} propuestas</p><div className="table-scroll"><table><caption className="sr-only">Propuestas del concurso</caption><thead><tr>{['Código','Participante','Edad','Localidad','Fecha','Propuesta','Entrega','Estado','Detalle'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td>{p.submission_code}</td><td>{p.full_name}</td><td>{p.age}</td><td>{p.city}</td><td>{new Date(p.created_at).toLocaleString('es-UY',{timeZone:'America/Montevideo'})}</td><td>{p.proposal_name||'Sin título'}</td><td>{p.submission_method==='file'?'Archivo':'Enlace'}</td><td>{statuses[p.status]}</td><td><button className="btn" onClick={()=>setSelected(p)}>Ver</button></td></tr>)}</tbody></table></div></>}
  </section>
}
