import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { contestConfig as c, contestState, dateLabel, safeUrl } from './config'
import { checklist, faq, tips } from './content'
import { track, type Result } from './api'
import { ContestForm } from './ContestForm'
import { Terms } from './Terms'
import './contest.css'
function Share() {
  const [notice,setNotice]=useState('')
  const text=`🎨 ¿Cómo representarías a las Mujeres Rurales de Flores? Participá del ${c.title}. 📍 Exclusivo para habitantes del departamento de Flores. ✅ Gratuito ✅ Sin límite de edad 🏆 Premio: ${c.prize} 📅 Hasta el ${dateLabel(c.closesAt)}. Creá. Participá. Representá. ${c.url}`
  return <section id="compartir"><h2>Compartí el concurso</h2><div className="actions"><a className="btn" target="_blank" rel="noopener noreferrer" href={`https://wa.me/?text=${encodeURIComponent(text)}`} onClick={()=>void track('share')}>Enviar por WhatsApp</a><a className="btn secondary" target="_blank" rel="noopener noreferrer" href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(c.url)}`} onClick={()=>void track('share')}>Facebook</a><button className="btn secondary" onClick={async()=>{try{await navigator.clipboard.writeText(c.url);setNotice('Enlace copiado.');void track('share')}catch{setNotice(c.url)}}}>Copiar enlace</button></div><p role="status">{notice}</p></section>
}
export default function ContestPage() {
  const [now,setNow]=useState(new Date()),[result,setResult]=useState<Result|null>(null)
  useEffect(()=>{const title=document.title;document.title=`${c.title} · Mujeres Rurales de Flores`;void track('visit');const id=setInterval(()=>setNow(new Date()),1000);if(supabase)void supabase.from('rural_women_results').select('*').eq('published',true).maybeSingle().then(({data})=>setResult(data));return()=>{clearInterval(id);document.title=title}},[])
  const state=contestState(now,Boolean(result)),remaining=Math.max(0,new Date(c.closesAt).getTime()-now.getTime()),days=Math.floor(remaining/86400000),hours=Math.floor(remaining%86400000/3600000)
  return <div className="contest"><a className="skip btn" href="#contenido">Saltar al contenido</a><div className="wrap"><nav aria-label="Navegación del concurso" className="actions"><Link to="/">← Rincón Te Escucha</Link><a href="#bases">Bases</a><a href="#cronograma">Fechas</a><a href="#preguntas">Preguntas frecuentes</a></nav><div className="logos"><div><small>ORGANIZA</small><img src={`${import.meta.env.BASE_URL}contest/juventud-transparent.png`} alt="Oficina de la Juventud · Intendencia Departamental de Flores"/></div><div><small>APOYA</small><img src={`${import.meta.env.BASE_URL}contest/desarrollo-transparent.png`} alt="Dirección de Promoción y Desarrollo · Intendencia Departamental de Flores"/></div></div>
    <main id="contenido"><div className="hero"><div><p className="eyebrow">{c.subtitle}</p><h1>¡Tu diseño puede representar a las Mujeres Rurales de Flores!</h1><p><strong>{c.title}</strong><br/>Buscamos una identidad visual que represente la diversidad, el trabajo, las raíces, el presente y el futuro de las Mujeres Rurales de nuestro departamento.</p><div className="chips">{['Para habitantes de Flores','Gratuito','Sin límite de edad','No necesitás ser diseñador/a'].map(t=><span key={t}>{t}</span>)}</div><div className="actions">{state==='open'&&<a className="btn" href="#inscripcion" onClick={()=>void track('start_click')}>Quiero participar ↗</a>}<a className="btn secondary" href="#bases" onClick={()=>void track('terms')}>Ver bases</a></div></div><figure className="poster"><a href={`${import.meta.env.BASE_URL}contest/placa-concurso.png`} target="_blank" rel="noopener noreferrer" aria-label="Ampliar la placa oficial del concurso (abre una pestaña nueva)"><img src={`${import.meta.env.BASE_URL}contest/placa-concurso.png`} width="1080" height="1350" alt="Placa oficial del concurso Mujeres Rurales de Flores: creá, participá, representá. Participación libre, sin límite de edad; cierre el 9 de octubre de 2026 y premio de USD 100."/></a><figcaption><p>Convocatoria exclusiva para habitantes del departamento de Flores.</p><a href={`${import.meta.env.BASE_URL}contest/placa-concurso.png`} target="_blank" rel="noopener noreferrer">Ampliar placa ↗</a><a href={`${import.meta.env.BASE_URL}contest/placa-concurso.png`} download>Descargar placa ↓</a></figcaption></figure></div>
    <div className="notice" role="status">{state==='open'?`Inscripciones abiertas · Quedan ${days} ${days===1?'día':'días'} · ${hours} ${hours===1?'hora':'horas'} para presentar tu diseño.`:state==='upcoming'?`La convocatoria abre el ${dateLabel(c.opensAt)}.`:state==='result'?'Ya tenemos una identidad ganadora.':'La convocatoria finalizó. Gracias a todas las personas que participaron. Estamos evaluando las propuestas recibidas.'}</div>
    {result&&<section><h2>Ya tenemos una identidad ganadora</h2>{safeUrl(result.image_url)&&<img className="preview" src={result.image_url} alt={`Diseño ganador: ${result.proposal_name}`}/>}<h3>{result.proposal_name}</h3><p>{result.author}</p><p>{result.rationale}</p>{result.mentions&&<p>Menciones especiales: {result.mentions}</p>}</section>}
    <section className="grid key-dates" aria-label="Fechas y premio">{[['Apertura',dateLabel(c.opensAt)],['Cierre',`${dateLabel(c.closesAt)} · 23:59 h`],['Premio',c.prize],['Resultado y premiación',dateLabel(c.awardAt)]].map(([k,v])=><div className="card" key={k}><p className="eyebrow">{k}</p><h3>{v}</h3></div>)}</section>
    <section className="how-to"><p className="eyebrow">Participar es sencillo</p><h2>Tu idea, en tres pasos</h2><ol className="grid"><li className="card"><span className="step-number">01</span><h3>Creá tu diseño</h3><p>A mano o con herramientas digitales. Elegí los elementos y colores que cuentan tu idea.</p></li><li className="card"><span className="step-number">02</span><h3>Contanos tu idea</h3><p>Explicá qué representa y cómo se relaciona con las Mujeres Rurales de Flores.</p></li><li className="card"><span className="step-number">03</span><h3>Enviá tu propuesta</h3><p>Completá el formulario y subí tu archivo o compartí un enlace.</p></li></ol>{state==='open'&&<a className="btn" href="#inscripcion" onClick={()=>void track('start_click')}>Quiero participar ↗</a>}</section>
    <section><div className="section-head"><p className="eyebrow">Mujeres Rurales de Flores</p><h2>{c.concept}</h2><p>No existe una única forma de representar a una Mujer Rural. Es productora, emprendedora, estudiante, profesional, trabajadora, artesana, cuidadora, dirigente, innovadora y referente comunitaria.</p></div><div className="chips">{'Territorio Comunidad Raíces Creatividad Trabajo Conocimiento Producción Cultura Innovación Igualdad Participación Autonomía Diversidad Futuro'.split(' ').map(t=><span key={t}>{t}</span>)}</div></section>
    <section className="grid"><div className="card"><h2>¿Vivís en el departamento de Flores?</h2><p>Pueden participar únicamente habitantes del departamento de Flores, tanto del medio urbano como del rural. Sin límite de edad y sin necesidad de ser diseñador/a ni tener experiencia en concursos. La participación es individual y gratuita.</p><p><strong>Si sos menor de 18 años, tu madre, padre o tutor legal debe completar y aceptar la autorización digital del formulario. Podés participar con ayuda de tu escuela, liceo o UTU.</strong></p></div><div className="card"><h2>¿Qué hay que presentar?</h2><p><strong>01 · Logo principal</strong><br/>Original e inédito.</p><p><strong>02 · Paleta de colores</strong><br/>Los colores principales. Sin necesidad de códigos profesionales.</p><p><strong>03 · Contanos tu idea</strong><br/>Una memoria conceptual de hasta 500 palabras.</p></div></section>
    <section><h2>Dos formas de entregar tu propuesta</h2><div className="grid"><div className="card"><h3>Subir archivos</h3><p>PNG, JPG/JPEG o PDF, hasta 10 MB por archivo. Diseño principal y material complementario opcional.</p></div><div className="card"><h3>Compartir un enlace</h3><p>Drive, Dropbox, OneDrive, WeTransfer, Canva, Adobe u otro servicio. Revisá sus permisos de acceso.</p></div></div><p className="muted">No necesitás un archivo vectorial profesional al participar. Si tu diseño es seleccionado, podrán solicitarse archivos originales, editables o de mayor resolución cuando existan.</p></section>
    <section id="cronograma"><div className="section-head"><p className="eyebrow">Agendá las fechas</p><h2>Del primer trazo a una identidad compartida</h2></div><div className="grid timeline">{[['Abre la convocatoria',dateLabel(c.opensAt)],['Cierran las propuestas',`${dateLabel(c.closesAt)} · 23:59 h`],['Evaluación',`${dateLabel(c.evaluationStart)} al ${dateLabel(c.evaluationEnd)}`],['Resultado y premiación',dateLabel(c.resultAt)]].map(([k,v],i)=><div key={k}><p className="eyebrow">0{i+1} / {k}</p><h3>{v}</h3></div>)}</div><p className="muted">Todas las fechas y horas corresponden a Uruguay.</p></section>
    <section className="jury-note"><h2>¿Cómo se elige el diseño?</h2><p>Las propuestas serán evaluadas por un jurado designado por la organización, de acuerdo con los criterios establecidos en las bases.</p><a href="#bases">Conocé los criterios de evaluación →</a></section>
    <section><div className="section-head"><p className="eyebrow">Tips para crear tu logo</p><h2>Antes de empezar…</h2></div><details className="tips-details"><summary>Explorá los 7 consejos para tu diseño</summary><div className="grid">{tips.map(([title,body],i)=><div className="card" key={title}><p className="eyebrow">0{i+1}</p><h3>{title}</h3><p>{body}</p></div>)}</div></details></section>
    <section><h2>¿Está listo tu diseño?</h2>{checklist.map(t=><label className="check" key={t}><input type="checkbox"/>{t}</label>)}{state==='open'&&<a className="btn" href="#inscripcion" onClick={()=>void track('start_click')}>Quiero participar ↗</a>}</section>
    <section id="inscripcion">{state==='open'?<ContestForm/>:<div className="card"><h2>{state==='upcoming'?'Pronto podrás presentar tu propuesta':'Convocatoria finalizada'}</h2><p>Consultá las fechas, las bases y las novedades en esta página.</p></div>}</section>
    <section id="preguntas"><h2>Preguntas frecuentes</h2>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
    <section id="bases"><h2>Bases del concurso</h2><details onToggle={e=>{if(e.currentTarget.open)void track('terms')}}><summary>Leer las bases completas online</summary><Terms/></details><a className="btn secondary" href={`${import.meta.env.BASE_URL}contest/bases.pdf`} download onClick={()=>void track('download')}>Descargar bases en PDF</a></section><Share/></main><footer className="card"><strong>{c.contact}</strong><p>Con el apoyo de la Dirección de Promoción y Desarrollo.</p><Link to={c.contactPath}>Contacto institucional</Link> · <Link to="/">Volver a Rincón Te Escucha</Link></footer>
  </div></div>
}
